packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - bcrypt
  - core-js-pure
  - esbuild
  - nestjs-pino
  - prisma
  - sharp
  - unrs-resolver
