name: hanul-dev
services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    container_name: hanul-dev
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy
      surf:
        condition: service_started
    volumes:
      - ../:/workspaces/hanul
    networks:
      - devnet
  db:
    image: postgres:17.5
    container_name: hanul-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: hanul
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev -d hanul']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - devnet
  surf:
    build:
      context: ../surf
      dockerfile: Dockerfile
    image: hanul-surf
    container_name: hanul-surf
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - DEBUG=False
      - AUTH_ENABLED=True
      - API_KEY=LOCAL_SURF_API_KEY
      - SEARCH_PROVIDER=duckduckgo
      - DUCKDUCKGO_TIMEOUT=15
      - DUCKDUCKGO_MAX_RESULTS=10
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/docs']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - surf-data:/app/data
    networks:
      - devnet
volumes:
  db-data:
  surf-data:
networks:
  devnet:
    driver: bridge
